name: "My Action"
description: "Test my action"
inputs:
  messages:
    description: "the message to print"
    required: true
    default: "Hola"

runs:
  using: "composite"
  
  steps:
    - name: Hola Mundo
      run: echo "Hola ${{ inputs.message }}"
      shell: bash