name: Test

on: [push]

jobs:
  tests-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: ls
        run: | 
          echo "Hola Mundo" >> holat.txt
          cat holat.txt
          ls -la
          chmod +x script.sh
          ./script.sh
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: latest
            
      - name: use node
        run: node --version