name: Test

on: [push]

jobs:
  tests-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: use actions
        uses: ./.github/actions/my-action
        with:
          message: "car"

      - name: ls
        run: | 
          echo "Hola Mundo" >> holat.txt
          cat holat.txt
          ls -la
          chmod +x script.sh
          ./script.sh
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: latest
            
      - name: use node
        run: node --version

      - name: Setup PHP
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: '8.3'

      - name: use php
        run: php --version
            