name: Secrets

on: [push]

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: secrets-steps
        run: echo "SECRETS ${{ secrets.MY_SECRET }}"
      - name: LS ssh_key
        run: echo "SSH KEY ${{ secrets.SSH_KEY }}"