name: WorkFlow GitHub Actions

on:
  push:
    branches:
      - main
      - pr

  pull_request:
    branches:
      - main
      - pr

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Step1
      run: echo "Hola Mundo"

    - name: Step2 touch File
      run: touch hola.txt

    - name: Step3 set text
      run: echo "Hola Mundo" >> hola.txt

    - name: Step4 Read File
      run: cat hola.txt

  job2:
    runs-on: ubuntu-latest
    needs: [job1]

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.1            
    - name: Step1 LS
      run: ls -al
